global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
  - job_name: my-application
    honor_labels: true
    static_configs:
      - targets: ["nodejs-application:5000", "nestjs-application:3000"]
        labels:
          group: "my-application"
